---
apiVersion: batch/v1
kind: Job
metadata:
  name: loadtest2
spec:
  template:
    spec:
      containers:
      - name: siege
        image: yokogawa/siege
        command: ["siege",  "--concurrent=5", "--benchmark", "--time=10m", "http://jino.com"]
      restartPolicy: Never
  backoffLimit: 4
