---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment2
  annotations:
    kubernetes.io/change-cause: nginx-v1.2

spec:
  strategy:
    type: RollingUpdate   # Other Option is Recreate is avaliable. Rolling Update is default option in deplouments
    rollingUpdate:
      maxSurge: 2         # maxSurge is an optional field that specifies the maximum number of Pods that can be created over the desired number of Pods.
      maxUnavailable: 1   # maxUnavailable is an optional field that specifies the maximum number of Pods that can be unavailable during the update process.
  revisionHistoryLimit: 4
  paused: false
  replicas: 3
  minReadySeconds: 10
  selector:
    matchLabels:
      role: webserver
    matchExpressions:
      - {key: version, operator: In, values: [v1, v2, v3]}
  template:
    metadata:
      name: web
      labels:
        role: webserver
        version: v1
        tier: frond-end
    spec:
      containers:
        - name: web
          image: nginx
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    role: web-service
spec:
  selector:
    role: webserver
    version: v1
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32001
  externalIPs:
    - 192.168.43.138
