---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-webserver
  labels:
    app: nginx
    tier: front-end
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    tier: front-end
    app: nginx
  ports:
    - port: 80
      nodePort: 32000
