apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: jino
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: public-ingress
  namespace: jino
spec:
  podSelector:
    matchExpressions:
      - {key: env, operator: In, values: [prod]}
  policyTypes:
  - Ingress
  ingress:
    - {}

