apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: httpd
    ports:
    - containerPort: 80
  initContainers:
  - name: init-myservice
    image: jjino/busybox:latest
    args:
    - bash
    - -c
    - while true; do STATUS=$(curl -s -o /dev/null -w '%{http_code}' http://kubernetesbyexample.com); if [ $STATUS -eq 200 ]; then  echo "Got 200! All done!"; break; else echo "Got $STATUS :( Not done yet..."; fi; sleep 10; done

---
apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  selector:
    app: myapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
