---
#single container to launch

apiVersion: v1
kind: Pod
metadata:
  name: web-pods
  labels:
    app: nginx
    tier: front
    version: v1
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
