---
#single pod with multiple container's
apiVersion: v1
kind: Pod
metadata:
  name: multicontainer-pods
  labels:
    app: nginx
    tier: frontend-backend
    version: v1
spec:
  containers:
  - name: web
    image: nginx
    ports:
      - containerPort: 80
  - name: db
    image: postgres
    ports:
      - containerPort: 5432
