apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    tier: front
    app: nginx
    role: ui
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP
      #volumeMounts:
      #  - name: webdata
      #    mountPath: /usr/share/nginx/html

    - name: db
      image: postgres
      ports:
        - containerPort: 5432
      volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data

  volumes:
    - name: data
      emptyDir: {}
