---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql:5
    ports:
      - containerPort: 3306
    envFrom:
      - configMapRef:
          name: mysql-credit
